[tool.poetry]
name = "image-processing-homography"
version = "0.1.0"
description = ""
authors = ["AnnexK <roadto3kmmr@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
